const grammarQuestions = [
    {
question:"『～にほかならない』の意味は？",
choices:["まさに～だ","～したい","～できない","～するべき"],
answer:0,
explanation:"～にほかならない＝まさにそれだ。"
},
{
question:"『～ざるを得ない』の意味は？",
choices:["仕方なく～する","絶対にしない","自由にする","希望する"],
answer:0,
explanation:"～ざるを得ない＝しないわけにはいかない。"
},
{
question:"『～に違いない』の意味は？",
choices:["きっと～だ","たぶん～ない","絶対に違う","不明だ"],
answer:0,
explanation:"強い推量を表す。"
},
{
question:"『～ものの』の意味は？",
choices:["けれども","だから","つまり","または"],
answer:0,
explanation:"逆接を表す。"
},
{
question:"『～に基づいて』の意味は？",
choices:["～を根拠として","～に反して","～を避けて","～の代わりに"],
answer:0,
explanation:"基準や根拠を表す。"
},
{
question:"『～に際して』の意味は？",
choices:["～の時に","～の後で","～の前に","～の途中で"],
answer:0,
explanation:"特別な機会を表す。"
},
{
question:"『～かねない』の意味は？",
choices:["悪い結果になる可能性がある","必ず成功する","希望している","禁止される"],
answer:0,
explanation:"悪い可能性を表す。"
},
{
question:"『～をめぐって』の意味は？",
choices:["～について","～から","～まで","～より"],
answer:0,
explanation:"議論や対立の対象。"
},
{
question:"『～に伴って』の意味は？",
choices:["～と一緒に変化して","～に反して","～を除いて","～の代わりに"],
answer:0,
explanation:"変化に合わせて。"
},
{
question:"『～に先立って』の意味は？",
choices:["～の前に","～の後で","～と同時に","～の途中で"],
answer:0,
explanation:"前もって行う。"
},
{
question:"『～に限らず』の意味は？",
choices:["～だけでなく","～だけ","～しか","～以外"],
answer:0,
explanation:"範囲を広げる表現。"
},
{
question:"『～を問わず』の意味は？",
choices:["関係なく","必ず","禁止して","限定して"],
answer:0,
explanation:"条件に関係ない。"
},
{
question:"『～に応じて』の意味は？",
choices:["～に合わせて","～に反して","～を避けて","～の代わりに"],
answer:0,
explanation:"状況に合わせる。"
},
{
question:"『～にわたって』の意味は？",
choices:["長い期間・広い範囲","短期間","一点だけ","限定的"],
answer:0,
explanation:"期間や範囲を表す。"
},
{
question:"『～を契機に』の意味は？",
choices:["きっかけとして","結果として","理由なく","途中で"],
answer:0,
explanation:"変化のきっかけ。"
},
{
question:"『～ことなく』の意味は？",
choices:["～しないで","～してから","～しながら","～するため"],
answer:0,
explanation:"動作をしないこと。"
},
{
question:"『～にかかわらず』の意味は？",
choices:["関係なく","必ず","限定して","比較して"],
answer:0,
explanation:"条件に左右されない。"
},
{
question:"『～のみならず』の意味は？",
choices:["～だけでなく","～だけ","～しか","～こそ"],
answer:0,
explanation:"追加を表す。"
},
{
question:"『～ばかりか』の意味は？",
choices:["～だけでなく","～しか","～だけ","～より"],
answer:0,
explanation:"さらに追加する。"
},
{
question:"『～どころか』の意味は？",
choices:["～どころではない","～だけ","～だから","～しか"],
answer:0,
explanation:"予想と反対。"
},
{
question:"『～にもかかわらず』の意味は？",
choices:["それなのに","だから","つまり","そのため"],
answer:0,
explanation:"逆接を表す。"
},
{
question:"『～つつある』の意味は？",
choices:["だんだん～している","終わった","始まらない","禁止された"],
answer:0,
explanation:"変化の途中。"
},
{
question:"『～つつ』の意味は？",
choices:["～しながら","～した後","～する前","～した結果"],
answer:0,
explanation:"同時進行。"
},
{
question:"『～かのようだ』の意味は？",
choices:["まるで～ようだ","絶対～だ","禁止する","命令する"],
answer:0,
explanation:"比喩表現。"
},
{
question:"『～にすぎない』の意味は？",
choices:["ただ～だけだ","非常に多い","必ず","十分だ"],
answer:0,
explanation:"程度が低い。"
},
{
question:"『～にほかならない』の意味は？",
choices:["まさに～だ","違う","禁止する","比較する"],
answer:0,
explanation:"強い断定。"
},
{
question:"『～にたえる』の意味は？",
choices:["十分価値がある","価値がない","禁止される","比較する"],
answer:0,
explanation:"評価に値する。"
},
{
question:"『～を余儀なくされる』の意味は？",
choices:["仕方なく～する","希望する","自由にする","禁止する"],
answer:0,
explanation:"強制される。"
},
{
question:"『～ないことには』の意味は？",
choices:["～しなければ","～しても","～するので","～だから"],
answer:0,
explanation:"必要条件。"
},
{
question:"『～ずにはいられない』の意味は？",
choices:["どうしても～してしまう","絶対しない","禁止する","比較する"],
answer:0,
explanation:"自然な感情。"
},
{
question:"『～てやまない』の意味は？",
choices:["強く願う","嫌う","比較する","避ける"],
answer:0,
explanation:"強い気持ち。"
},
{
question:"『～にこたえて』の意味は？",
choices:["期待に応じて","反対して","避けて","比較して"],
answer:0,
explanation:"要望などに応じる。"
},
{
question:"『～に沿って』の意味は？",
choices:["基準に従って","反対して","避けて","比較して"],
answer:0,
explanation:"方針などに従う。"
},
{
question:"『～に反して』の意味は？",
choices:["逆らって","従って","合わせて","比較して"],
answer:0,
explanation:"期待や方針と逆。"
},
{
question:"『～に比べて』の意味は？",
choices:["比較すると","従うと","避けると","反対すると"],
answer:0,
explanation:"比較を表す。"
},
{
question:"『～にかけては』の意味は？",
choices:["～について言えば","～の後で","～の途中で","～の前で"],
answer:0,
explanation:"得意分野を表す。"
},
{
question:"『～にほど』の意味は？",
choices:["～くらい","～だけ","～しか","～より"],
answer:0,
explanation:"程度を表す。"
},
{
question:"『～に即して』の意味は？",
choices:["実情に合わせて","反対して","比較して","避けて"],
answer:0,
explanation:"現実に合わせる。"
},
{
question:"『～を通じて』の意味は？",
choices:["全期間・手段として","途中だけ","最後だけ","最初だけ"],
answer:0,
explanation:"期間や手段。"
},
{
question:"『～を通して』の意味は？",
choices:["手段として","禁止して","比較して","反対して"],
answer:0,
explanation:"媒介を表す。"
},
{
question:"『～にあたって』の意味は？",
choices:["その時に","その後で","その前に","途中で"],
answer:0,
explanation:"重要な機会。"
},
{
question:"『～に際し』の意味は？",
choices:["～の時に","～の後で","～の前に","途中で"],
answer:0,
explanation:"改まった表現。"
},
{
question:"『～末に』の意味は？",
choices:["長い過程の結果","開始時","途中","直後"],
answer:0,
explanation:"苦労した結果。"
},
{
question:"『～あげく』の意味は？",
choices:["悪い結果になる","成功する","途中で終わる","開始する"],
answer:0,
explanation:"望ましくない結果。"
},
{
question:"『～限り』の意味は？",
choices:["範囲では","禁止","比較","命令"],
answer:0,
explanation:"知る範囲など。"
},
{
question:"『～限りでは』の意味は？",
choices:["～の範囲で判断すると","必ず","比較して","禁止して"],
answer:0,
explanation:"限定した判断。"
},
{
question:"『～以上』の意味は？",
choices:["～なのだから","比較","反対","条件なし"],
answer:0,
explanation:"理由を表す。"
},
{
question:"『～上は』の意味は？",
choices:["～した以上","比較","反対","途中"],
answer:0,
explanation:"責任や決意。"
},
{
question:"『～からには』の意味は？",
choices:["～なのだから","比較","禁止","途中"],
answer:0,
explanation:"当然の結果。"
},
{
question:"『～からして』の意味は？",
choices:["それ自体から判断して","比較","反対","途中"],
answer:0,
explanation:"代表例を示す。"
},
{
question:"『～ことだから』の意味は？",
choices:["～なので当然","比較","反対","途中"],
answer:0,
explanation:"その人なら当然そうだという意味。"
},
{
question:"『～ものだから』の意味は？",
choices:["言い訳・理由","比較","反対","途中"],
answer:0,
explanation:"理由を説明する表現。"
},
{
question:"『～だけあって』の意味は？",
choices:["さすがに","比較","反対","途中"],
answer:0,
explanation:"期待どおりの結果。"
},
{
question:"『～だけに』の意味は？",
choices:["それだけの理由で","比較","反対","途中"],
answer:0,
explanation:"理由が強調される。"
},
{
question:"『～だけのことはある』の意味は？",
choices:["それに見合う価値がある","比較","反対","途中"],
answer:0,
explanation:"努力しただけの結果がある。"
},
{
question:"『～わけだ』の意味は？",
choices:["当然そうなる","比較","反対","途中"],
answer:0,
explanation:"納得の結論。"
},
{
question:"『～わけではない』の意味は？",
choices:["必ずしもそうではない","比較","反対","途中"],
answer:0,
explanation:"部分否定。"
},
{
question:"『～ないわけではない』の意味は？",
choices:["少しはそうだ","比較","反対","途中"],
answer:0,
explanation:"完全否定ではない。"
},
{
question:"『～というわけではない』の意味は？",
choices:["必ずしもそうではない","比較","反対","途中"],
answer:0,
explanation:"断定を避ける。"
},
{
question:"『～わけにはいかない』の意味は？",
choices:["できない事情がある","比較","反対","途中"],
answer:0,
explanation:"社会的理由でできない。"
},
{
question:"『～ないではすまない』の意味は？",
choices:["必ず必要になる","比較","反対","途中"],
answer:0,
explanation:"避けられない。"
},
{
question:"『～ないではおかない』の意味は？",
choices:["必ずそうなる","比較","反対","途中"],
answer:0,
explanation:"強い意志や結果。"
},
{
question:"『～に決まっている』の意味は？",
choices:["絶対そうだ","比較","反対","途中"],
answer:0,
explanation:"強い確信。"
},
{
question:"『～に相違ない』の意味は？",
choices:["きっとそうだ","比較","反対","途中"],
answer:0,
explanation:"強い推量。"
},
{
question:"『～に違いない』の意味は？",
choices:["きっとそうだ","比較","反対","途中"],
answer:0,
explanation:"確信に近い推量。"
},
{
question:"『～まい』の意味は？",
choices:["～しないだろう","比較","反対","途中"],
answer:0,
explanation:"否定の推量。"
},
{
question:"『～べく』の意味は？",
choices:["～するために","比較","反対","途中"],
answer:0,
explanation:"目的を表す硬い表現。"
},
{
question:"『～べくもない』の意味は？",
choices:["できるはずがない","比較","反対","途中"],
answer:0,
explanation:"不可能を表す。"
},
{
question:"『～んがため』の意味は？",
choices:["～するために","比較","反対","途中"],
answer:0,
explanation:"非常に硬い目的表現。"
},
{
question:"『～んばかりだ』の意味は？",
choices:["今にも～しそう","比較","反対","途中"],
answer:0,
explanation:"直前の様子。"
},
{
question:"『～を皮切りに』の意味は？",
choices:["最初として","比較","反対","途中"],
answer:0,
explanation:"始まりを表す。"
},
{
question:"『～をもって』の意味は？",
choices:["その時点で","比較","反対","途中"],
answer:0,
explanation:"終了や基準を表す。"
},
{
question:"『～を禁じ得ない』の意味は？",
choices:["感情を抑えられない","比較","反対","途中"],
answer:0,
explanation:"感情が自然に出る。"
},
{
question:"『～にもまして』の意味は？",
choices:["それ以上に","比較","反対","途中"],
answer:0,
explanation:"程度が上。"
},
{
question:"『～にも増して』の意味は？",
choices:["以前よりさらに","比較","反対","途中"],
answer:0,
explanation:"比較表現。"
},
{
question:"『～ならでは』の意味は？",
choices:["～だからこそ","比較","反対","途中"],
answer:0,
explanation:"特有の特徴。"
},
{
question:"『～なしには』の意味は？",
choices:["～がなければ","比較","反対","途中"],
answer:0,
explanation:"必要条件。"
},
{
question:"『～なくしては』の意味は？",
choices:["～がなければ","比較","反対","途中"],
answer:0,
explanation:"必要条件。"
},
{
question:"『～ならまだしも』の意味は？",
choices:["～なら理解できるが","比較","反対","途中"],
answer:0,
explanation:"対比を表す。"
},
{
question:"『～といえども』の意味は？",
choices:["～であっても","比較","反対","途中"],
answer:0,
explanation:"逆接。"
},
{
question:"『～とはいえ』の意味は？",
choices:["そうは言っても","比較","反対","途中"],
answer:0,
explanation:"譲歩表現。"
},
{
question:"『～とはいうものの』の意味は？",
choices:["そう言うが","比較","反対","途中"],
answer:0,
explanation:"逆接。"
},
{
question:"『～にしろ』の意味は？",
choices:["～であっても","比較","反対","途中"],
answer:0,
explanation:"譲歩。"
},
{
question:"『～にせよ』の意味は？",
choices:["～であっても","比較","反対","途中"],
answer:0,
explanation:"譲歩。"
},
{
question:"『～にしても』の意味は？",
choices:["～としても","比較","反対","途中"],
answer:0,
explanation:"仮定。"
},
{
question:"『～としても』の意味は？",
choices:["仮に～でも","比較","反対","途中"],
answer:0,
explanation:"仮定条件。"
},
{
question:"『～ものを』の意味は？",
choices:["残念・非難","比較","反対","途中"],
answer:0,
explanation:"後悔や不満。"
},
{
question:"『～くせに』の意味は？",
choices:["非難","比較","反対","途中"],
answer:0,
explanation:"不満を表す。"
},
{
question:"『～ながらも』の意味は？",
choices:["けれども","比較","反対","途中"],
answer:0,
explanation:"逆接。"
},
{
question:"『～ものの』の意味は？",
choices:["けれども","比較","反対","途中"],
answer:0,
explanation:"逆接。"
},
{
question:"『～反面』の意味は？",
choices:["一方で","比較","反対","途中"],
answer:0,
explanation:"対照的な面。"
},
{
question:"『～一方だ』の意味は？",
choices:["ますます～する","比較","反対","途中"],
answer:0,
explanation:"変化が続く。"
},
{
question:"『～ばかりだ』の意味は？",
choices:["ますます～する","比較","反対","途中"],
answer:0,
explanation:"変化の継続。"
},
{
question:"『～次第だ』の意味は？",
choices:["結果としてそうなった","比較","反対","途中"],
answer:0,
explanation:"事情説明。"
},
{
question:"『～次第で』の意味は？",
choices:["～によって決まる","比較","反対","途中"],
answer:0,
explanation:"条件次第。"
},
{
question:"『～ところだ』の意味は？",
choices:["ちょうどその段階","比較","反対","途中"],
answer:0,
explanation:"動作の段階。"
},
{
question:"『～ところを』の意味は？",
choices:["本来なら～だが","比較","反対","途中"],
answer:0,
explanation:"感謝や謝罪で使う。"
},
{
question:"『～が最後』の意味は？",
choices:["一度～したら","比較","反対","途中"],
answer:0,
explanation:"強い条件。"
},
{
question:"『～や否や』の意味は？",
choices:["するとすぐ","比較","反対","途中"],
answer:0,
explanation:"直後を表す。"
},
{
question:"『～そばから』の意味は？",
choices:["すぐ後で","比較","反対","途中"],
answer:0,
explanation:"繰り返し起こる。"
}
];