const kanjiQuestions = [{
question:"懸念の読み方は？",
choices:["けねん","こんねん","けんねん","げねん"],
answer:0,
explanation:"懸念（けねん）＝心配すること。"
},
{
question:"顕著の読み方は？",
choices:["けんちょ","げんちょ","けんしょう","げんしょう"],
answer:0,
explanation:"顕著（けんちょ）＝はっきり目立つこと。"
},
{
question:"踏襲の読み方は？",
choices:["とうしゅう","ふしゅう","とうしょう","ふとう"],
answer:0,
explanation:"踏襲（とうしゅう）＝前のやり方を受け継ぐこと。"
},
{
question:"遂行の読み方は？",
choices:["すいこう","ついこう","ずいこう","すいぎょう"],
answer:0,
explanation:"遂行（すいこう）＝最後までやり遂げること。"
},
{
question:"把握の読み方は？",
choices:["はあく","ばあく","はかく","ばかく"],
answer:0,
explanation:"把握（はあく）＝理解すること。"
},
{
question:"妥当の読み方は？",
choices:["だとう","たいとう","たとう","だどう"],
answer:0,
explanation:"妥当（だとう）＝適切なこと。"
},
{
question:"網羅の読み方は？",
choices:["もうら","こうら","ぼうら","もうだ"],
answer:0,
explanation:"網羅（もうら）＝漏れなく含むこと。"
},
{
question:"享受の読み方は？",
choices:["きょうじゅ","きょうう","こうじゅ","きょじゅ"],
answer:0,
explanation:"享受（きょうじゅ）＝利益を受けること。"
},
{
question:"露呈の読み方は？",
choices:["ろてい","ろしょう","ろじ","ろせい"],
answer:0,
explanation:"露呈（ろてい）＝明らかになること。"
},
{
question:"刷新の読み方は？",
choices:["さっしん","こうしん","しんさつ","さつしん"],
answer:0,
explanation:"刷新（さっしん）＝新しく改めること。"
},
{
question:"膠着の読み方は？",
choices:["こうちゃく","こうじゃく","きょうちゃく","こうせき"],
answer:0,
explanation:"膠着（こうちゃく）＝物事が進まないこと。"
},
{
question:"脆弱の読み方は？",
choices:["ぜいじゃく","せいじゃく","ぜいしゃく","さいじゃく"],
answer:0,
explanation:"脆弱（ぜいじゃく）＝弱いこと。"
},
{
question:"精査の読み方は？",
choices:["せいさ","しょうさ","せいしゃ","しょうしゃ"],
answer:0,
explanation:"精査（せいさ）＝詳しく調べること。"
},
{
question:"勘案の読み方は？",
choices:["かんあん","かんなん","こんあん","こうあん"],
answer:0,
explanation:"勘案（かんあん）＝考慮すること。"
},
{
question:"是正の読み方は？",
choices:["ぜせい","ぜしょう","ぜいせい","せせい"],
answer:0,
explanation:"是正（ぜせい）＝正しく直すこと。"
},
{
question:"遵守の読み方は？",
choices:["じゅんしゅ","そんしゅ","じゅんす","じゅんじゅ"],
answer:0,
explanation:"遵守（じゅんしゅ）＝守ること。"
},
{
question:"補填の読み方は？",
choices:["ほてん","ほうてん","ふてん","ほちん"],
answer:0,
explanation:"補填（ほてん）＝不足を補うこと。"
},
{
question:"懐柔の読み方は？",
choices:["かいじゅう","かいにゅう","かいじゅ","かいゆう"],
answer:0,
explanation:"懐柔（かいじゅう）＝うまく従わせること。"
},
{
question:"干渉の読み方は？",
choices:["かんしょう","かんじょう","かんそう","かんせい"],
answer:0,
explanation:"干渉（かんしょう）＝口出しすること。"
},
{
question:"逸脱の読み方は？",
choices:["いつだつ","いちだつ","いつたつ","いったつ"],
answer:0,
explanation:"逸脱（いつだつ）＝基準から外れること。"
},
{
question:"模索の読み方は？",
choices:["もさく","ぼさく","もそう","ぼそう"],
answer:0,
explanation:"模索（もさく）＝探し求めること。"
},
{
question:"顧慮の読み方は？",
choices:["こりょ","ころ","こりょう","ころう"],
answer:0,
explanation:"顧慮（こりょ）＝よく考えること。"
},
{
question:"緻密の読み方は？",
choices:["ちみつ","しみつ","ちみつう","じみつ"],
answer:0,
explanation:"緻密（ちみつ）＝細かく正確なこと。"
},
{
question:"潜在の読み方は？",
choices:["せんざい","せんさい","ぜんざい","ぜんさい"],
answer:0,
explanation:"潜在（せんざい）＝隠れて存在すること。"
},
{
question:"多岐の読み方は？",
choices:["たき","たぎ","だき","だぎ"],
answer:0,
explanation:"多岐（たき）＝多方面。"
},
{
question:"簡潔の読み方は？",
choices:["かんけつ","かんせつ","けんけつ","けんせつ"],
answer:0,
explanation:"簡潔（かんけつ）＝短く分かりやすいこと。"
},
{
question:"漠然の読み方は？",
choices:["ばくぜん","ぼくぜん","ばくせん","ぼくせん"],
answer:0,
explanation:"漠然（ばくぜん）＝ぼんやりしていること。"
},
{
question:"暫定の読み方は？",
choices:["ざんてい","さんてい","ざんじょう","さんじょう"],
answer:0,
explanation:"暫定（ざんてい）＝仮のこと。"
},
{
question:"膨大の読み方は？",
choices:["ぼうだい","ほうだい","ぼだい","ほだい"],
answer:0,
explanation:"膨大（ぼうだい）＝非常に多いこと。"
},
{
question:"迅速の読み方は？",
choices:["じんそく","しんそく","じんぞく","しんぞく"],
answer:0,
explanation:"迅速（じんそく）＝素早いこと。"
},
{
question:"慎重の読み方は？",
choices:["しんちょう","じんちょう","しんしょう","じんしょう"],
answer:0,
explanation:"慎重（しんちょう）＝注意深いこと。"
},
{
question:"軽率の読み方は？",
choices:["けいそつ","けいりつ","けいさつ","けいせつ"],
answer:0,
explanation:"軽率（けいそつ）＝考えが浅いこと。"
},
{
question:"弊害の読み方は？",
choices:["へいがい","はいがい","へいかい","はいかい"],
answer:0,
explanation:"弊害（へいがい）＝悪い影響。"
},
{
question:"恩恵の読み方は？",
choices:["おんけい","おんえ","おんけ","おんけつ"],
answer:0,
explanation:"恩恵（おんけい）＝利益や恵み。"
},
{
question:"容認の読み方は？",
choices:["ようにん","ようじん","ように","ようじ"],
answer:0,
explanation:"容認（ようにん）＝認めること。"
},
{
question:"一貫の読み方は？",
choices:["いっかん","いちかん","いっこう","いちこう"],
answer:0,
explanation:"一貫（いっかん）＝同じ方針を保つこと。"
},
{
question:"懇願の読み方は？",
choices:["こんがん","こうがん","こんげん","こうげん"],
answer:0,
explanation:"懇願（こんがん）＝強くお願いすること。"
},
{
question:"堅実の読み方は？",
choices:["けんじつ","けんしつ","かたじつ","かたしつ"],
answer:0,
explanation:"堅実（けんじつ）＝確実でまじめなこと。"
},
{
question:"抽象の読み方は？",
choices:["ちゅうしょう","ちょうしょう","ちゅうぞう","ちょうぞう"],
answer:0,
explanation:"抽象（ちゅうしょう）＝具体性がないこと。"
},
{
question:"具現化の読み方は？",
choices:["ぐげんか","ぐんげんか","ぐげんけ","ぐんげんけ"],
answer:0,
explanation:"具現化（ぐげんか）＝実現すること。"
},
{
question:"一掃の読み方は？",
choices:["いっそう","いちそう","いっしょう","いちしょう"],
answer:0,
explanation:"一掃（いっそう）＝全部取り除くこと。"
},
{
question:"余儀なくされるの読み方は？",
choices:["よぎなくされる","よぎりなくされる","よぎなされる","よぎされる"],
answer:0,
explanation:"余儀なくされる＝仕方なくする。"
},
{
question:"蓄積の読み方は？",
choices:["ちくせき","ちょくせき","ちくしゃく","ちょくしゃく"],
answer:0,
explanation:"蓄積（ちくせき）＝ためること。"
},
{
question:"懐疑の読み方は？",
choices:["かいぎ","かいぎい","かぎ","かいき"],
answer:0,
explanation:"懐疑（かいぎ）＝疑うこと。"
},
{
question:"柔軟性の読み方は？",
choices:["じゅうなんせい","じゅなんせい","にゅうなんせい","じゅうだんせい"],
answer:0,
explanation:"柔軟性（じゅうなんせい）＝対応力。"
},
{
question:"着手の読み方は？",
choices:["ちゃくしゅ","ちゃくて","ちゃくじゅ","ちゃくしゅう"],
answer:0,
explanation:"着手（ちゃくしゅ）＝始めること。"
},
{
question:"見解の読み方は？",
choices:["けんかい","みかい","けんげ","みげ"],
answer:0,
explanation:"見解（けんかい）＝考え方や意見。"
},
{
question:"打開の読み方は？",
choices:["だかい","たかい","だがい","たがい"],
answer:0,
explanation:"打開（だかい）＝困難な状況を切り開くこと。"
},
{
question:"紛争の読み方は？",
choices:["ふんそう","ぶんそう","ふんしょう","ぶんしょう"],
answer:0,
explanation:"紛争（ふんそう）＝争いごと。"
},
{
question:"著名の読み方は？",
choices:["ちょめい","しょめい","ちょうめい","じょめい"],
answer:0,
explanation:"著名（ちょめい）＝有名なこと。"
},
{
question:"懲戒の読み方は？",
choices:["ちょうかい","しょうかい","ちょうがい","しょうがい"],
answer:0,
explanation:"懲戒（ちょうかい）＝罰すること。"
},
{
question:"履行の読み方は？",
choices:["りこう","りぎょう","りこうう","りぎょうう"],
answer:0,
explanation:"履行（りこう）＝約束を実行すること。"
},
{
question:"改訂の読み方は？",
choices:["かいてい","かいてつ","がいてい","がいてつ"],
answer:0,
explanation:"改訂（かいてい）＝内容を改めること。"
},
{
question:"進展の読み方は？",
choices:["しんてん","しんでん","じんてん","じんでん"],
answer:0,
explanation:"進展（しんてん）＝物事が進むこと。"
},
{
question:"起因の読み方は？",
choices:["きいん","きげん","きおん","きえん"],
answer:0,
explanation:"起因（きいん）＝原因となること。"
},
{
question:"明瞭の読み方は？",
choices:["めいりょう","みょうりょう","めいろう","みょうろう"],
answer:0,
explanation:"明瞭（めいりょう）＝はっきりしていること。"
},
{
question:"漸次の読み方は？",
choices:["ぜんじ","せんじ","ぜんし","せんし"],
answer:0,
explanation:"漸次（ぜんじ）＝少しずつ。"
},
{
question:"勃発の読み方は？",
choices:["ぼっぱつ","ほっぱつ","ぼつぱつ","ほつぱつ"],
answer:0,
explanation:"勃発（ぼっぱつ）＝突然起こること。"
},
{
question:"妥協の読み方は？",
choices:["だきょう","たきょう","だこう","たこう"],
answer:0,
explanation:"妥協（だきょう）＝譲り合うこと。"
},
{
question:"躍進の読み方は？",
choices:["やくしん","ようしん","やっしん","よう進"],
answer:0,
explanation:"躍進（やくしん）＝大きく進歩すること。"
},
{
question:"均衡の読み方は？",
choices:["きんこう","きんごう","こんこう","こんごう"],
answer:0,
explanation:"均衡（きんこう）＝バランス。"
},
{
question:"拡充の読み方は？",
choices:["かくじゅう","こうじゅう","かくちゅう","こうちゅう"],
answer:0,
explanation:"拡充（かくじゅう）＝広げて充実させること。"
},
{
question:"偏見の読み方は？",
choices:["へんけん","へんげん","べんけん","べんげん"],
answer:0,
explanation:"偏見（へんけん）＝かたよった考え。"
},
{
question:"帰属の読み方は？",
choices:["きぞく","きしょく","きそく","きぞう"],
answer:0,
explanation:"帰属（きぞく）＝所属すること。"
},
{
question:"派生の読み方は？",
choices:["はせい","はいせい","はしょう","はいしょう"],
answer:0,
explanation:"派生（はせい）＝元から生じること。"
},
{
question:"真摯の読み方は？",
choices:["しんし","しんじ","まし","まじ"],
answer:0,
explanation:"真摯（しんし）＝真面目で誠実。"
},
{
question:"繁栄の読み方は？",
choices:["はんえい","ばんえい","はんよう","ばんよう"],
answer:0,
explanation:"繁栄（はんえい）＝栄えること。"
},
{
question:"排除の読み方は？",
choices:["はいじょ","ばいじょ","はいしょ","ばいしょ"],
answer:0,
explanation:"排除（はいじょ）＝取り除くこと。"
},
{
question:"軽減の読み方は？",
choices:["けいげん","けいけん","きょうげん","けんげん"],
answer:0,
explanation:"軽減（けいげん）＝軽くすること。"
},
{
question:"繁忙の読み方は？",
choices:["はんぼう","ばんぼう","はんもう","ばんもう"],
answer:0,
explanation:"繁忙（はんぼう）＝忙しいこと。"
},
{
question:"阻止の読み方は？",
choices:["そし","そじ","しょし","しょじ"],
answer:0,
explanation:"阻止（そし）＝防ぎ止めること。"
},
{
question:"脅威の読み方は？",
choices:["きょうい","ぎょうい","きょうえ","ぎょうえ"],
answer:0,
explanation:"脅威（きょうい）＝おそれ。"
},
{
question:"措置の読み方は？",
choices:["そち","しょち","そうち","しょうち"],
answer:0,
explanation:"措置（そち）＝必要な処置。"
},
{
question:"顕在化の読み方は？",
choices:["けんざいか","げんざいか","けんさいか","げんさいか"],
answer:0,
explanation:"顕在化（けんざいか）＝表面に現れること。"
},
{
question:"柔軟の読み方は？",
choices:["じゅうなん","にゅうなん","じゅなん","にゅなん"],
answer:0,
explanation:"柔軟（じゅうなん）＝しなやかなこと。"
},
{
question:"徹底の読み方は？",
choices:["てってい","てつてい","てっしょう","てつしょう"],
answer:0,
explanation:"徹底（てってい）＝十分に行うこと。"
},
{
question:"著しいの読み方は？",
choices:["いちじるしい","ちょしい","しるしい","あらわしい"],
answer:0,
explanation:"著しい（いちじるしい）＝目立つこと。"
},
{
question:"反映の読み方は？",
choices:["はんえい","ばんえい","はんよう","ばんよう"],
answer:0,
explanation:"反映（はんえい）＝結果として現れること。"
},
{
question:"阻害の読み方は？",
choices:["そがい","しょうがい","そかい","しょうかい"],
answer:0,
explanation:"阻害（そがい）＝妨げること。"
},
{
question:"促すの読み方は？",
choices:["うながす","そくす","うごかす","すすめる"],
answer:0,
explanation:"促す（うながす）＝行動をうながすこと。"
},
{
question:"一律の読み方は？",
choices:["いちりつ","いちりゅう","いっりつ","いっりゅう"],
answer:0,
explanation:"一律（いちりつ）＝すべて同じこと。"
},
{
question:"逸話の読み方は？",
choices:["いつわ","いちわ","いつばなし","いちばなし"],
answer:0,
explanation:"逸話（いつわ）＝興味深い話。"
},
{
question:"従来の読み方は？",
choices:["じゅうらい","しょうらい","じょうらい","じゅらい"],
answer:0,
explanation:"従来（じゅうらい）＝これまで。"
},
{
question:"一概にの読み方は？",
choices:["いちがいに","いちかいに","いっがいに","いっかいに"],
answer:0,
explanation:"一概に（いちがいに）＝同じようには言えないこと。"
},
{
question:"妨げるの読み方は？",
choices:["さまたげる","ぼうげる","じゃまげる","とどめる"],
answer:0,
explanation:"妨げる（さまたげる）＝邪魔すること。"
},
{
question:"促成の読み方は？",
choices:["そくせい","そくしょう","しょくせい","しょくしょう"],
answer:0,
explanation:"促成（そくせい）＝早く育てること。"
},
{
question:"明確の読み方は？",
choices:["めいかく","みょうかく","めいがく","みょうがく"],
answer:0,
explanation:"明確（めいかく）＝はっきりしていること。"
},
{
question:"簡略の読み方は？",
choices:["かんりゃく","けんりゃく","かんりょく","けんりょく"],
answer:0,
explanation:"簡略（かんりゃく）＝簡単にすること。"
},
{
question:"保全の読み方は？",
choices:["ほぜん","ほせん","ぼぜん","ぼせん"],
answer:0,
explanation:"保全（ほぜん）＝守ること。"
},
{
question:"継承の読み方は？",
choices:["けいしょう","けいじょう","けしょう","けじょう"],
answer:0,
explanation:"継承（けいしょう）＝受け継ぐこと。"
},
{
question:"収束の読み方は？",
choices:["しゅうそく","しゅうぞく","じゅうそく","じゅうぞく"],
answer:0,
explanation:"収束（しゅうそく）＝落ち着くこと。"
},
{
question:"網羅的の読み方は？",
choices:["もうらてき","こうらてき","ぼうらてき","もうだてき"],
answer:0,
explanation:"網羅的（もうらてき）＝漏れなく含む様子。"
},
{
question:"勘違いの読み方は？",
choices:["かんちがい","こんちがい","かんじがい","こんじがい"],
answer:0,
explanation:"勘違い（かんちがい）＝思い違い。"
},
{
question:"簡便の読み方は？",
choices:["かんべん","けんべん","かんへん","けんへん"],
answer:0,
explanation:"簡便（かんべん）＝簡単で便利なこと。"
},
{
question:"均一の読み方は？",
choices:["きんいつ","きんいち","こんいつ","こんいち"],
answer:0,
explanation:"均一（きんいつ）＝すべて同じ状態。"
},
{
question:"顧客の読み方は？",
choices:["こきゃく","こかく","こぎゃく","こうきゃく"],
answer:0,
explanation:"顧客（こきゃく）＝お客様。"
},
{
question:"概況の読み方は？",
choices:["がいきょう","かいきょう","がいこう","かいこう"],
answer:0,
explanation:"概況（がいきょう）＝全体の様子。"
}
];