const vocabularyQuestions = [{
question:"顕著の意味は？",
choices:["はっきり目立つ","隠れている","弱い","静か"],
answer:0,
explanation:"顕著は『はっきりと目立つこと』。"
},
{
question:"懸念の意味は？",
choices:["心配","希望","安心","期待"],
answer:0,
explanation:"懸念は気がかりなこと。"
},
{
question:"踏襲の意味は？",
choices:["受け継ぐ","破棄する","変更する","無視する"],
answer:0,
explanation:"踏襲は従来の方法を受け継ぐこと。"
},
{
question:"遂行の意味は？",
choices:["やり遂げる","延期する","中止する","妨害する"],
answer:0,
explanation:"遂行は最後まで実行すること。"
},
{
question:"把握の意味は？",
choices:["理解する","忘れる","否定する","放棄する"],
answer:0,
explanation:"把握は内容を理解すること。"
},
{
question:"配慮の意味は？",
choices:["気を配る","命令する","拒否する","放置する"],
answer:0,
explanation:"配慮は相手や状況に気を配ること。"
},
{
question:"妥当の意味は？",
choices:["適切","危険","不正","異常"],
answer:0,
explanation:"妥当は適切であること。"
},
{
question:"抑制の意味は？",
choices:["おさえる","広げる","増やす","放任する"],
answer:0,
explanation:"抑制は勢いなどをおさえること。"
},
{
question:"促進の意味は？",
choices:["進める","止める","戻す","壊す"],
answer:0,
explanation:"促進は物事を進めること。"
},
{
question:"概略の意味は？",
choices:["大まかな内容","詳細","誤り","結論"],
answer:0,
explanation:"概略は大まかな内容。"
},
{
question:"網羅の意味は？",
choices:["漏れなく含む","削除する","隠す","分割する"],
answer:0,
explanation:"網羅は必要なものをすべて含むこと。"
},
{
question:"享受の意味は？",
choices:["利益を受ける","拒否する","失う","与える"],
answer:0,
explanation:"享受は利益や恩恵を受けること。"
},
{
question:"露呈の意味は？",
choices:["明らかになる","隠れる","消える","改善する"],
answer:0,
explanation:"露呈は隠れていたものが現れること。"
},
{
question:"刷新の意味は？",
choices:["新しくする","維持する","停止する","削除する"],
answer:0,
explanation:"刷新は新しく改めること。"
},
{
question:"膠着の意味は？",
choices:["進まない状態","急速に進む","成功する","解決する"],
answer:0,
explanation:"膠着は物事が進まない状態。"
},
{
question:"脆弱の意味は？",
choices:["弱い","強い","安全","頑丈"],
answer:0,
explanation:"脆弱は弱く壊れやすいこと。"
},
{
question:"精査の意味は？",
choices:["詳しく調べる","隠す","削除する","放置する"],
answer:0,
explanation:"精査は細かく調べること。"
},
{
question:"勘案の意味は？",
choices:["考慮する","否定する","忘れる","命令する"],
answer:0,
explanation:"勘案は事情を考慮すること。"
},
{
question:"是正の意味は？",
choices:["正しく直す","悪化させる","削除する","延期する"],
answer:0,
explanation:"是正は悪い点を正しく直すこと。"
},
{
question:"遵守の意味は？",
choices:["守る","破る","変更する","忘れる"],
answer:0,
explanation:"遵守は規則などを守ること。"
},
{
question:"補填の意味は？",
choices:["不足を補う","減らす","壊す","捨てる"],
answer:0,
explanation:"補填は不足分を補うこと。"
},
{
question:"懐柔の意味は？",
choices:["うまく従わせる","攻撃する","無視する","拒否する"],
answer:0,
explanation:"懐柔は相手を味方につけること。"
},
{
question:"干渉の意味は？",
choices:["口出しする","応援する","協力する","観察する"],
answer:0,
explanation:"干渉は他人のことに立ち入ること。"
},
{
question:"逸脱の意味は？",
choices:["外れる","一致する","改善する","近づく"],
answer:0,
explanation:"逸脱は基準などから外れること。"
},
{
question:"模索の意味は？",
choices:["探し求める","完成する","放棄する","拒絶する"],
answer:0,
explanation:"模索は方法などを探すこと。"
},
{
question:"顧慮の意味は？",
choices:["よく考える","忘れる","否定する","放置する"],
answer:0,
explanation:"顧慮は気を配り考えること。"
},
{
question:"緻密の意味は？",
choices:["細かく正確","大雑把","曖昧","危険"],
answer:0,
explanation:"緻密は細かく丁寧なこと。"
},
{
question:"潜在の意味は？",
choices:["隠れて存在する","表面化する","完成する","終了する"],
answer:0,
explanation:"潜在は表面に出ていない状態。"
},
{
question:"多岐の意味は？",
choices:["多方面","単一","少数","限定"],
answer:0,
explanation:"多岐は多方面にわたること。"
},
{
question:"簡潔の意味は？",
choices:["短く分かりやすい","長い","複雑","難解"],
answer:0,
explanation:"簡潔は要点がまとまっていること。"
},
{
question:"漠然の意味は？",
choices:["ぼんやり","明確","具体的","正確"],
answer:0,
explanation:"漠然ははっきりしない様子。"
},
{
question:"暫定の意味は？",
choices:["仮の","永久の","正式の","確定した"],
answer:0,
explanation:"暫定は一時的なこと。"
},
{
question:"膨大の意味は？",
choices:["非常に多い","少ない","不足","限定"],
answer:0,
explanation:"膨大は非常に量が多いこと。"
},
{
question:"迅速の意味は？",
choices:["素早い","遅い","危険","慎重"],
answer:0,
explanation:"迅速は素早いこと。"
},
{
question:"慎重の意味は？",
choices:["注意深い","乱暴","軽率","無計画"],
answer:0,
explanation:"慎重は注意深く行うこと。"
},
{
question:"軽率の意味は？",
choices:["考えが浅い","慎重","正確","丁寧"],
answer:0,
explanation:"軽率はよく考えないこと。"
},
{
question:"弊害の意味は？",
choices:["悪い影響","良い影響","利益","改善"],
answer:0,
explanation:"弊害は悪い影響。"
},
{
question:"恩恵の意味は？",
choices:["利益や恵み","損失","危険","失敗"],
answer:0,
explanation:"恩恵は受ける利益。"
},
{
question:"容認の意味は？",
choices:["認める","拒否する","攻撃する","禁止する"],
answer:0,
explanation:"容認は認めること。"
},
{
question:"一貫の意味は？",
choices:["同じ方針を保つ","変更する","中断する","対立する"],
answer:0,
explanation:"一貫は最初から最後まで同じこと。"
},
{
question:"懇願の意味は？",
choices:["強くお願いする","断る","怒る","批判する"],
answer:0,
explanation:"懇願は強く頼むこと。"
},
{
question:"堅実の意味は？",
choices:["確実でまじめ","危険","派手","無計画"],
answer:0,
explanation:"堅実は確実で信頼できること。"
},
{
question:"抽象の意味は？",
choices:["具体性がない","明確","詳細","現実的"],
answer:0,
explanation:"抽象は具体的でないこと。"
},
{
question:"具現化の意味は？",
choices:["実現する","削除する","延期する","否定する"],
answer:0,
explanation:"具現化は形にして表すこと。"
},
{
question:"一掃の意味は？",
choices:["全部取り除く","追加する","保存する","支援する"],
answer:0,
explanation:"一掃は全部取り除くこと。"
},
{
question:"余儀なくされるの意味は？",
choices:["仕方なくする","自由にする","楽しむ","拒否する"],
answer:0,
explanation:"余儀なくされるは仕方なくそうすること。"
},
{
question:"蓄積の意味は？",
choices:["ためる","減らす","失う","放棄する"],
answer:0,
explanation:"蓄積は少しずつためること。"
},
{
question:"懐疑の意味は？",
choices:["疑うこと","信じること","期待すること","応援すること"],
answer:0,
explanation:"懐疑は疑いを持つこと。"
},
{
question:"柔軟性の意味は？",
choices:["対応力","支配力","攻撃力","集中力"],
answer:0,
explanation:"柔軟性は状況に応じて変化できること。"
},
{
question:"着手の意味は？",
choices:["始める","終わる","中断する","拒否する"],
answer:0,
explanation:"着手は取り掛かること。"
},
{
question:"見解の意味は？",
choices:["考え方や意見","契約","命令","法律"],
answer:0,
explanation:"見解は考え方や意見。"
},
{
question:"打開の意味は？",
choices:["困難を解決する","中止する","延期する","拒否する"],
answer:0,
explanation:"打開は困難な状況を切り開くこと。"
},
{
question:"紛争の意味は？",
choices:["争い","協力","成功","調和"],
answer:0,
explanation:"紛争は争いごと。"
},
{
question:"著名の意味は？",
choices:["有名","無名","平凡","不明"],
answer:0,
explanation:"著名は有名なこと。"
},
{
question:"懲戒の意味は？",
choices:["罰する","褒める","助ける","許可する"],
answer:0,
explanation:"懲戒は規則違反などを罰すること。"
},
{
question:"履行の意味は？",
choices:["約束を実行する","拒否する","忘れる","延期する"],
answer:0,
explanation:"履行は契約や義務を実行すること。"
},
{
question:"改訂の意味は？",
choices:["内容を改める","維持する","削除する","中止する"],
answer:0,
explanation:"改訂は内容を修正すること。"
},
{
question:"進展の意味は？",
choices:["進むこと","止まること","後退すること","失敗すること"],
answer:0,
explanation:"進展は物事が進むこと。"
},
{
question:"起因の意味は？",
choices:["原因となる","終了する","完成する","解決する"],
answer:0,
explanation:"起因は原因となること。"
},
{
question:"明瞭の意味は？",
choices:["はっきりしている","曖昧","不明","複雑"],
answer:0,
explanation:"明瞭ははっきりしていること。"
},
{
question:"漸次の意味は？",
choices:["少しずつ","急に","突然","完全に"],
answer:0,
explanation:"漸次は少しずつ進むこと。"
},
{
question:"勃発の意味は？",
choices:["突然起こる","静かになる","終了する","解決する"],
answer:0,
explanation:"勃発は事件などが突然起こること。"
},
{
question:"妥協の意味は？",
choices:["譲り合う","対立する","拒否する","無視する"],
answer:0,
explanation:"妥協は互いに譲り合うこと。"
},
{
question:"躍進の意味は？",
choices:["大きく進歩する","後退する","停止する","失敗する"],
answer:0,
explanation:"躍進は大きく進歩すること。"
},
{
question:"均衡の意味は？",
choices:["バランス","混乱","対立","崩壊"],
answer:0,
explanation:"均衡はつり合いが取れている状態。"
},
{
question:"拡充の意味は？",
choices:["広げて充実させる","縮小する","停止する","拒否する"],
answer:0,
explanation:"拡充は規模や内容を広げること。"
},
{
question:"偏見の意味は？",
choices:["かたよった考え","公平な判断","分析","研究"],
answer:0,
explanation:"偏見はかたよった見方。"
},
{
question:"帰属の意味は？",
choices:["所属する","離脱する","対立する","排除する"],
answer:0,
explanation:"帰属は所属すること。"
},
{
question:"派生の意味は？",
choices:["元から生じる","消滅する","終了する","破壊する"],
answer:0,
explanation:"派生は元のものから生じること。"
},
{
question:"真摯の意味は？",
choices:["真面目で誠実","怠惰","軽率","乱暴"],
answer:0,
explanation:"真摯は真面目で誠実なこと。"
},
{
question:"繁栄の意味は？",
choices:["栄える","衰える","停止する","失敗する"],
answer:0,
explanation:"繁栄は豊かに発展すること。"
},
{
question:"排除の意味は？",
choices:["取り除く","追加する","保存する","維持する"],
answer:0,
explanation:"排除は取り除くこと。"
},
{
question:"軽減の意味は？",
choices:["軽くする","重くする","増やす","悪化させる"],
answer:0,
explanation:"軽減は負担などを軽くすること。"
},
{
question:"繁忙の意味は？",
choices:["忙しいこと","暇なこと","危険なこと","静かなこと"],
answer:0,
explanation:"繁忙は非常に忙しいこと。"
},
{
question:"阻止の意味は？",
choices:["防ぎ止める","進める","許可する","維持する"],
answer:0,
explanation:"阻止は防ぎ止めること。"
},
{
question:"遂行の類義語は？",
choices:["実行","放棄","拒否","停止"],
answer:0,
explanation:"遂行は実行してやり遂げること。"
},
{
question:"遵守の反対は？",
choices:["違反","順守","尊重","維持"],
answer:0,
explanation:"遵守の反対は違反。"
},
{
question:"配慮の類義語は？",
choices:["気遣い","無視","放置","拒絶"],
answer:0,
explanation:"配慮は気遣いのこと。"
},
{
question:"恩恵の反対に近い意味は？",
choices:["損害","利益","成功","幸福"],
answer:0,
explanation:"恩恵の反対は損害や不利益。"
},
{
question:"抑制の反対は？",
choices:["促進","停止","削減","中断"],
answer:0,
explanation:"抑制の反対は促進。"
},
{
question:"顕著の類義語は？",
choices:["著しい","曖昧","微弱","平凡"],
answer:0,
explanation:"顕著と著しいは似た意味。"
},
{
question:"脅威の意味は？",
choices:["おそれ","安心","期待","成功"],
answer:0,
explanation:"脅威はおそれや危険。"
},
{
question:"措置の意味は？",
choices:["必要な処置","反省","提案","分析"],
answer:0,
explanation:"措置は必要な対応をすること。"
},
{
question:"顕在化の意味は？",
choices:["表面化する","隠れる","消える","縮小する"],
answer:0,
explanation:"顕在化は問題などが表面に現れること。"
},
{
question:"柔軟の意味は？",
choices:["しなやか","頑固","危険","複雑"],
answer:0,
explanation:"柔軟は考え方などが柔らかいこと。"
},
{
question:"徹底の意味は？",
choices:["十分に行う","途中でやめる","簡単にする","無視する"],
answer:0,
explanation:"徹底は隅々まで十分に行うこと。"
},
{
question:"著しいの意味は？",
choices:["目立つ","静か","小さい","弱い"],
answer:0,
explanation:"著しいは非常に目立つこと。"
},
{
question:"反映の意味は？",
choices:["結果として現れる","隠す","拒否する","削除する"],
answer:0,
explanation:"反映は結果や意見を表すこと。"
},
{
question:"阻害の意味は？",
choices:["妨げる","助ける","促進する","支援する"],
answer:0,
explanation:"阻害は妨げること。"
},
{
question:"促すの意味は？",
choices:["うながす","拒否する","止める","壊す"],
answer:0,
explanation:"促すは行動をうながすこと。"
},
{
question:"一律の意味は？",
choices:["すべて同じ","個別","自由","例外"],
answer:0,
explanation:"一律はすべて同じ扱いをすること。"
},
{
question:"逸話の意味は？",
choices:["興味深い話","法律","規則","契約"],
answer:0,
explanation:"逸話は人物に関する面白い話。"
},
{
question:"従来の意味は？",
choices:["これまで","これから","未来","仮定"],
answer:0,
explanation:"従来はこれまでのこと。"
},
{
question:"一概にの意味は？",
choices:["一律には言えない","完全に","確実に","絶対に"],
answer:0,
explanation:"一概には同じようには言えないという意味。"
},
{
question:"妨げるの意味は？",
choices:["邪魔する","助ける","守る","導く"],
answer:0,
explanation:"妨げるは邪魔すること。"
},
{
question:"促成の意味は？",
choices:["早く育てる","遅らせる","維持する","停止する"],
answer:0,
explanation:"促成は通常より早く成長させること。"
},
{
question:"明確の意味は？",
choices:["はっきりしている","曖昧","不正確","不明"],
answer:0,
explanation:"明確ははっきりしていること。"
},
{
question:"簡略の意味は？",
choices:["簡単にする","複雑にする","削除する","延期する"],
answer:0,
explanation:"簡略は簡単にまとめること。"
},
{
question:"保全の意味は？",
choices:["守ること","破壊すること","削除すること","中止すること"],
answer:0,
explanation:"保全は良い状態を保つこと。"
},
{
question:"継承の意味は？",
choices:["受け継ぐ","放棄する","否定する","変更する"],
answer:0,
explanation:"継承は受け継ぐこと。"
},
{
question:"収束の意味は？",
choices:["落ち着く","広がる","増加する","悪化する"],
answer:0,
explanation:"収束は物事が落ち着くこと。"
}

];